#!/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest"
apt-get -y update
yes no | apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Setup coturn"
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
mv /etc/turnserver.conf /etc/turnserver.conf.bak
mv /usr/local/var/tmp/turnserver.conf /etc/turnserver.conf

echo "* Disable ssh"
service ssh stop
systemctl disable ssh

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
rm -rf /usr/local/var/tmp/*
history -c
