#!/bin/bash

set -o errexit

export LC_ALL=en_US.utf8
export LANGUAGE=en_US.utf8
export LANG=en_US.utf8

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

echo "* Get latest"
apt-get -y update
yes no | apt-get -y upgrade
apt-get -y dist-upgrade

echo "* Setup coturn"
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
mkdir -p /etc/coturn
chown -R turnserver:turnserver /etc/coturn
cp /etc/turnserver.conf /etc/turnserver.conf.bak
sed -i \
    -e "s|PIDFile=/run/turnserver/turnserver.pid|#PIDFile=/run/turnserver/turnserver.pid|" \
    -e "s|ExecStartPost=/bin/sleep 2|ExecStartPost=/bin/sleep 4|" \
    /etc/systemd/system/coturn.service
systemctl reset-failed coturn.service || true
systemctl daemon-reload || true

echo "* Disable and remove rpcbind"
apt-get -y remove rpcbind || true
systemctl stop rpcbind.service
systemctl disable rpcbind.service

echo "* Disable nfs-client"
systemctl unmask nfs-client.target
systemctl disable nfs-client.target

echo "* Disable ssh"
systemctl stop ssh
systemctl disable ssh

echo "* Ensure bootstrap will run next time"
rm -rf /var/lib/bootstrap

echo "* Cleaning up."
history -c
